config/routes.rb
AuctionAppSecondGo::Application.routes.draw do
  root 'auctions#index'

  get "register" => "users#new"
  post "users/" => "users#create"

  get "users/:id/edit" => "users#edit", :as => "edit_user"

  patch "users/:id" => "users#update", :as => "user"
  delete "users/:id" => "users#destroy"

  get "log_in" => "sessions#new"
  post "sessions/" => "sessions#create"
  delete "sessions/" => "sessions#destroy", :as => "log_out"

  get "auctions/" => "auctions#index"
  post "auctions/" => "auctions#create"

  get "auctions/new" => "auctions#new", :as => "new_auction"
  get "auctions/:id/edit" => "auctions#edit", :as => "edit_auction"

  get "auctions/:id" => "auctions#show", :as => "auction"
  patch "auctions/:id" => "auctions#update"
  delete "auctions/:id" => "auctions#destroy"

  post "auctions/:auction_id/bids/" => "bids#create", :as => "auction_bid"
  get "auctions/:auction_id/bids/new" => "bids#new", :as => "new_auction_bid"
  get "bids/:id" => "bids#show", :as => "bid"

end

app/models/auction.rb
class Auction < ActiveRecord::Base
  validates_presence_of :title, :end_time
  validates_uniqueness_of :title
  validate :has_not_ended
  belongs_to :seller, :class_name => "User"
  has_many :bids

  def ended?
    self.end_time < Time.now
  end

  def has_not_ended
    errors.add(:end_time, "must be in the future.") if ended?
  end

  def current_bid 
    bids.where(amount: bids.maximum(:amount)).first
  end
end

app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :bidder, :class_name=> "User"
  belongs_to :auction
  validates_numericality_of :amount
  validates_presence_of :bidder_id, :auction_id, :amount
  validate :high_enough
  validate :auction_not_ended?
  validate :amount_numeric

  def highest_bid_amount
    self.auction.bids.maximum(:amount)
  end

  def high_enough
    if highest_bid_amount && self.amount
      if highest_bid_amount > self.amount
        errors.add(:amount, "must exceed current bid.")
      end
    end
  end

  def auction_not_ended?
    errors[:auction] = "must not have ended" if auction.ended?
  end

  def amount_in_dollars
    self.amount.to_i / 100 if self.amount
  end

  def amount_in_dollars=(amount_in_dollars)
    # numericality lost here if not saved to instance variable
    # 1) money in database integer, float, or string?
    # 2) numericality validations only work on strings b/c activerecord
    # typecasting?
    @amount_in_dollars = amount_in_dollars
    self.amount = amount_in_dollars.to_i * 100
  end

  def amount_numeric
    unless @amount_in_dollars.match(/\A[+-]?\d+\Z/)
      errors.add(:amount, "must be numeric")
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_uniqueness_of :email
  validates_presence_of :email, :name, :password, :password_confirmation

  has_many :listings, :class_name => "Auction", :foreign_key => "seller_id"
  has_many :bids, :foreign_key => "bidder_id"
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :log_in, :logged_in?, :current_user, :logged_in_with_id?

  def log_in user
    session[:user_id] = user.id
  end

  def logged_in?
    !!session[:user_id]
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if logged_in?
  end

  def current_user? user
    current_user == user
  end

  def log_out!
    reset_session
  end

  def require_login
    redirect_to log_in_path, :notice => "Please sign in." unless logged_in?
  end

  def logged_in_with_id? id
    current_user && current_user.id == id
  end

end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_action :set_auction, :only => [:show, :edit, :update, :destroy]
  before_action :require_login, :only => [:create, :new]
  before_action :authenticate_seller, :only => [:edit, :update, :destroy]

  def index
    @auctions = Auction.all
  end

  def new
    @auction = Auction.new
  end

  def create
    @auction = Auction.new(auction_params)
    @auction.seller_id = current_user.id
    if @auction.save
      redirect_to auctions_path, :notice => "Auction successfully created"
    else
      render :new
    end
  end

  def show
    @current_bid = @auction.current_bid
    @bid = Bid.new
  end

  def edit
  end
  
  def update
    if @auction.update(auction_params)
      redirect_to auctions_path, :notice => "Auction successfully updated"
    else
      render :edit
    end
  end

  def destroy
    unless logged_in_with_id? @auction.seller_id
      redirect_to auctions_path
    else
      @auction.destroy
      redirect_to auctions_path
    end
  end

  private
  def auction_params
    params.require(:auction).permit(:title, :description, :end_time)
  end

  def set_auction
    @auction = Auction.find(params[:id])
  end

  def authenticate_seller
    if !logged_in_with_id? @auction.seller_id
      redirect_to auctions_path, :notice => "You may not edit another user's listing." 
    end
  end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :set_auction
  before_action :require_login
  before_action :authenticate_bidder

  def create
    @bid = Bid.new(bid_params)
    @bid.auction_id = @auction.id
    @bid.bidder_id = current_user.id if current_user
    if @bid.save
      redirect_to @auction, :notice => "You successfully submitted a bid!"
    else
      render 'auctions/show' 
    end
  end

  private

  def bid_params
    params.require(:bid).permit(:amount_in_dollars)
  end

  def set_auction
    @auction = Auction.find(params[:auction_id])
  end

  def authenticate_bidder
    if logged_in_with_id? @auction.seller.id
      flash.now[:notice] = "You may not bid on your own items."
      @bid = Bid.new
      render 'auctions/show'
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(:email => params[:email])
    if @user && @user.authenticate(params[:password])
      log_in @user
      redirect_to auctions_path
    else
      flash.now[:notice] = "Password and email don't match."
      @user = User.new
      render 'sessions/new'
    end
  end

  def destroy
    log_out!
    redirect_to auctions_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, :only => [:edit, :update, :destroy]
  def new
    @user = User.new
  end

  #login user
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to auctions_path
    else
      render :new
    end
  end

  #require login
  def edit

  end

  #require login
  def update
    if @user.update(user_params)
      redirect_to auctions_path
    else
      render :edit
    end
  end

  #require login
  def destroy
    @user.destroy
    redirect_to auctions_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_errors.html.erb
<div class="panel panel-danger">
  <div class="panel-heading">Errors</div>
  <div class="panel-body">
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/auctions/_auction.html.erb
<tr>
  <td><%= auction.title %></td>
  <td><%= auction.description %></td>
  <td><%= auction.end_time %></td>
  <td><%= auction.seller.email %></td>
  <td><%= link_to "show", auction %></td>
  <% if logged_in_with_id? auction.seller_id %>
    <td><%= link_to "edit", edit_auction_path(auction) %></td>
    <td><%= link_to "delete", auction, :method => "Delete" %></td>
  <% else %>
    <td></td>
    <td></td>
  <% end %>
</tr>

app/views/auctions/_form.html.erb
<div class="row">
  <div class="col-xs-6">
    <%= form_for(@auction) do |t| %>

      <div class="form-group">
        <%= t.label :title %>
        <%= t.text_field :title, :class => "form-control" %>
      </div>

      <div class="form-group">
        <%= t.label :description %>
        <%= t.text_field :description, :class => "form-control"%>
      </div>

      <div class="form-group">
        <%= t.label :end_date %>
        <%= t.datetime_select :end_time, :class => "form-control"%>
      </div>

      <%= t.submit "Submit" , :class => "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/auctions/edit.html.erb
<h1>Edit Auction</h1>
<%= render 'form' %>

app/views/auctions/index.html.erb
<h1>Auctions</h1>
<table class="table">
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>End Time</th>
    <th>Seller</th>
    <th><!-- show --></th>
    <th><!-- edit --></th>
    <th><!-- delete --></th>
  </tr>
  <%= render @auctions %>

</table>

<%= link_to "Create Auction", new_auction_path, :class => "btn btn-primary" %>

app/views/auctions/new.html.erb
<h1>New Auction</h1>

<%= render :partial => 'errors', :locals => { :object => @auction } if @auction.errors.any? %>
<%= render 'form' %>

app/views/auctions/show.html.erb
<h1><%= @auction.title %></h1>
<table class="table">
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>End Time</th>
    <th>Seller</th>
    <th><!-- show --></th>
    <th><!-- edit --></th>
    <th><!-- delete --></th>
  </tr>
  <%= render @auction %>
</table>

<div class="row">
  <div class="well col-xs-4">
    <% if @auction.current_bid %>
      <%= render @auction.current_bid %>
    <% else %>
      <h2>No bids.</h2>
    <% end %>
    <% unless logged_in? && current_user == @auction.seller %>
      <%= render :partial => 'errors', :locals => { :object => @bid } if @bid.errors.any? %>
      <%= render :partial => "bids/form" %>
    <% end %>
  </div>
</div>

app/views/bids/_bid.html.erb
<h3>Current Bid: $<%= @auction.current_bid.amount_in_dollars %></h3>
<h5><%= @auction.current_bid.bidder.email %></h5>

app/views/bids/_form.html.erb
<%= form_for @bid, :url => "/auctions/#{@auction.id}/bids" do |f| %>
  <div class="form-group">
    <%= f.label :amount %>
    <%= text_field_tag "bid[amount_in_dollars]", nil, :class => "form-control" %>
  </div>
  <%= f.submit "Place Bid", :class => "btn btn-primary", :data => { :confirm => "Are you sure?" } %>
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse">
      <%= render 'layouts/navigation_links' %>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<ul class="nav navbar-nav">

</ul>

<ul class="nav navbar-nav navbar-right">
  <% if logged_in? %>
    <li><%= link_to current_user.email, edit_user_path(current_user) %></li>
    <li><%= link_to "log out", sessions_path, :method => "Delete" %>
  <% else %>
    <li><%= link_to "register", register_path %></li>
    <li><%= link_to "log in", log_in_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Auction App Second Go" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Auction App Second Go" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    </main>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => "form-control" %>
    <%= f.label :email %>
    <%= f.text_field :email, :class => "form-control" %>
    <%= f.label :password %>
    <%= f.password_field :password, :class => "form-control" %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, :class => "form-control" %>
  </div>
  <%= f.submit :class => "btn btn-success"%>
<% end %>

app/views/users/edit.html.erb
<h1>Account</h1>
<h3>Edit your account n' stuff.</h3>

<%= render :partial => 'errors', 
           :locals => { :object => @user } if @user.errors.any? %>
<%= render 'form' %>

<br>
<%= link_to "Destroy Account!!!", user_path(@user), :method => "Delete",
  :class => "btn btn-danger",
  :data => { :confirm => "Are you sure?  What about your BeeNee Babez?" }%>

app/views/users/new.html.erb
<div class="row">
  <div class="col-xs-5 col-xs-offset-1">
    <h1>Register</h1>
    <h3>Sell all your beanie babies.</h3>

    <%= render :partial => "errors", :locals => { :object => @user } if @user.errors.any? %>
    <%= render :partial => 'users/form' %>

  </div>
</div>